apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qwiu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qwiu
    app.kubernetes.io/part-of: ci10t-777-0055-app
  name: devfile-sample-qwiu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qwiu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qwiu
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0055-tenant/ci10t-777-0055-app/devfile-sample-qwiu@sha256:642b8417ccfee7036250240dce1e414e42ffffb2c9454367580c60371e6bfc9d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
